version: "3"

services:
  app:
    build:
      context: .
      target: "dev"
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules

    container_name: "Component-Compound"
    ports:
      - 3000:3000
