version: "3"

services:
  app:
    build:
      context: .
      target: "dev"
      dockerfile: Dockerfile
    volumes:
      - .:/app/

    container_name: "Compound-Component-Pattern"
    ports:
      - 3000:3000
